import { useState, useEffect } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { collection, query, where, getDocs, orderBy } from 'firebase/firestore';
import { db } from '../../firebase';
import BillListItem from '../../components/bills/BillListItem';
import Card from '../../components/ui/Card';
import LoadingSpinner from '../../components/ui/LoadingSpinner';
import EmptyState from '../../components/ui/EmptyState';
import { FiFileText, FiFilter } from 'react-icons/fi';

// Define the shape of the bill data for this page
import type { Bill } from '../../types/bill';

const TenantBillsPage = () => {
  const { currentUser } = useAuth();
  const [bills, setBills] = useState<Bill[]>([]);
  const [filteredBills, setFilteredBills] = useState<Bill[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeFilter, setActiveFilter] = useState<'all' | 'paid' | 'due' | 'overdue'>('all');
  const [searchTerm, setSearchTerm] = useState('');

  useEffect(() => {
    const fetchBillsAndUnits = async () => {
      if (!currentUser) {
        setIsLoading(false);
        return;
      }
      
      setIsLoading(true);
      try {
        // Step 1: Fetch all units and create a map of [unitId -> unitName] for efficient lookup
        const unitsSnapshot = await getDocs(collection(db, 'units'));
        const unitMap = new Map<string, string>();
        unitsSnapshot.forEach(doc => {
          unitMap.set(doc.id, doc.data().unitName);
        });

        // Step 2: Fetch all bills for the current user, ordered by most recent first
        let billsSnapshot;
        
        // Try to find bills by UID
        let q = query(
          collection(db, 'bills'),
          where('tenantId', '==', currentUser.uid),
          orderBy('billDate', 'desc')
        );
        billsSnapshot = await getDocs(q);
        
        // If no bills found by UID and user has email, try by email
        if (billsSnapshot.empty && currentUser.email) {
          console.log("No bills found by UID, trying email");
          q = query(
            collection(db, 'bills'),
            where('tenantEmail', '==', currentUser.email),
            orderBy('billDate', 'desc')
          );
          billsSnapshot = await getDocs(q);
        }
        
        // Step 3: Combine bill data with the unit name from our map
        const billsList = billsSnapshot.docs.map(doc => {
          const data = doc.data() as Record<string, unknown>;
          return {
            id: doc.id,
            ...data,
            unitName: unitMap.get(data.unitId as string) || 'Unknown Unit', // Look up the unit name
            rentAmount: typeof data.rentAmount === 'number' ? data.rentAmount : Number(data.rentAmount) || 0,
            overdueCharges: typeof data.overdueCharges === 'number' ? data.overdueCharges : Number(data.overdueCharges) || 0,
          } as Bill;
        });
        
        setBills(billsList);

      } catch (err) {
        console.error("Error fetching bills:", err);
        setError("Could not load your bill history. Please try again later.");
      } finally {
        setIsLoading(false);
      }
    };

    fetchBillsAndUnits();
  }, [currentUser]); // Re-run this effect if the user changes

  // Filter bills when filter or search changes
  useEffect(() => {
    let filtered = bills;

    // Apply status filter
    if (activeFilter !== 'all') {
      filtered = filtered.filter(bill => bill.status === activeFilter);
    }

    // Apply search filter
    if (searchTerm) {
      filtered = filtered.filter(bill => 
        bill.billId?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        bill.unitName?.toLowerCase().includes(searchTerm.toLowerCase())
      );
    }

    setFilteredBills(filtered);
  }, [bills, activeFilter, searchTerm]);

  const renderContent = () => {
    if (isLoading) {
      return <LoadingSpinner text="Loading your bill history..." />;
    }
  
    if (error) {
      return <Card><p className="text-danger text-center">{error}</p></Card>;
    }

    if (bills.length === 0) {
      return (
        <EmptyState
          icon={FiFileText}
          title="No Bills Yet"
          description="You don't have any bill history yet. Bills will appear here once they are generated by your property manager."
        />
      );
    }

    if (filteredBills.length === 0) {
      return (
        <Card>
          <p className="text-text-secondary text-center py-8">
            No bills found matching your filters. Try adjusting your search or filter criteria.
          </p>
        </Card>
      );
    }
    
    return (
      <div className="space-y-4">
        {filteredBills.map(bill => (
          <BillListItem key={bill.id} bill={bill} />
        ))}
      </div>
    );
  };

  return (
    <div>
      <h1 className="text-3xl font-bold font-secondary mb-6">Bills & Payments</h1>
      
      {!isLoading && bills.length > 0 && (
        <>
          {/* Search Bar */}
          <Card className="mb-6">
            <div className="flex items-center">
              <FiFilter className="text-text-secondary mr-3" size={20} />
              <input
                type="text"
                placeholder="Search by bill ID or unit name..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary"
              />
            </div>
          </Card>

          {/* Filter Tabs */}
          <div className="flex flex-wrap gap-2 mb-6">
            <button
              onClick={() => setActiveFilter('all')}
              className={`px-4 py-2 rounded-lg font-semibold transition-all ${
                activeFilter === 'all'
                  ? 'bg-primary text-white shadow-md'
                  : 'bg-surface text-text-secondary hover:bg-gray-100'
              }`}
            >
              All Bills ({bills.length})
            </button>
            <button
              onClick={() => setActiveFilter('paid')}
              className={`px-4 py-2 rounded-lg font-semibold transition-all ${
                activeFilter === 'paid'
                  ? 'bg-success text-white shadow-md'
                  : 'bg-surface text-text-secondary hover:bg-gray-100'
              }`}
            >
              Paid ({bills.filter(b => b.status === 'paid').length})
            </button>
            <button
              onClick={() => setActiveFilter('due')}
              className={`px-4 py-2 rounded-lg font-semibold transition-all ${
                activeFilter === 'due'
                  ? 'bg-yellow-500 text-white shadow-md'
                  : 'bg-surface text-text-secondary hover:bg-gray-100'
              }`}
            >
              Due ({bills.filter(b => b.status === 'due').length})
            </button>
            <button
              onClick={() => setActiveFilter('overdue')}
              className={`px-4 py-2 rounded-lg font-semibold transition-all ${
                activeFilter === 'overdue'
                  ? 'bg-danger text-white shadow-md'
                  : 'bg-surface text-text-secondary hover:bg-gray-100'
              }`}
            >
              Overdue ({bills.filter(b => b.status === 'overdue').length})
            </button>
          </div>
        </>
      )}

      {renderContent()}
    </div>
  );
};

export default TenantBillsPage;